import { expect, test, type Page } from '@playwright/test'

const AHORA = new Date('2026-10-05T11:30:00Z')
async function abrir(page: Page, url: string) {
  const errores: string[] = []
  page.on('pageerror', e => errores.push(String(e)))
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.clock.install({ time: AHORA })
  await page.route('**/*', route => {
    const u = new URL(route.request().url())
    if (!['localhost', '127.0.0.1'].includes(u.hostname)) return route.abort()
    if (u.pathname.startsWith('/api/')) return route.fulfill({ status: 503, json: { error: 'Synthetic backend unavailable.' } })
    return route.continue()
  })
  await page.goto(url)
  return errores
}
for (const width of [390, 1280]) test.describe(`FAQ y material disponible a ${width}px`, () => {
  test.use({ viewport: { width, height: 844 } })
  test('FAQ se consulta con teclado, usa criterios guardados y carga el índice a petición', async ({ page }) => {
    const errores = await abrir(page, '/?escena=abierto#ajustes')
    await expect(page.getByRole('heading', { name: 'Ajustes', exact: true })).toBeVisible()
    const faq = page.getByRole('region', { name: 'Preguntas frecuentes', exact: true })
    await expect(faq).toBeVisible()
    const antes = await page.evaluate(() => ({ estudio: window.__leerProgresoSintetico(), nbme: window.__leerNbmeSintetico() }))
    for (const titulo of ['Dominio y aprendizaje', 'Meta y círculos', 'Hoy y repasos', 'Sesiones, IA y cuenta']) {
      await expect(faq.getByRole('heading', { name: titulo, exact: true })).toBeVisible()
    }
    await expect(faq.locator('details')).toHaveCount(13)
    await expect(faq.locator('details[open]')).toHaveCount(0)
    const diferencia = faq.locator('summary').filter({ hasText: '¿Qué diferencia hay entre visto, práctica y dominio?' })
    await diferencia.focus(); await diferencia.press('Enter')
    await expect(diferencia.locator('..')).toHaveAttribute('open', '')
    await expect(diferencia.locator('..')).toContainText('Una recomendación en una lista no lo cuenta')
    const dominio = faq.locator('details').filter({ has: page.locator('summary').filter({ hasText: '¿Qué necesito para demostrar dominio?' }) })
    await dominio.locator('summary').focus(); await dominio.locator('summary').press('Space')
    await expect(dominio).toContainText('3 respuestas independientes correctas en 2 sesiones distintas')
    await expect(dominio).toContainText('48 horas')
    await page.getByText('Criterios de dominio (avanzado)', { exact: true }).click()
    await page.getByLabel('Respuestas independientes correctas mínimas').fill('2')
    await expect(dominio).toContainText('3 respuestas independientes correctas')
    await page.getByRole('button', { name: 'Cancelar cambios', exact: true }).click()
    for (const summary of await faq.locator('summary').all()) expect((await summary.boundingBox())!.height).toBeGreaterThanOrEqual(44)
    expect(await page.evaluate(() => window.__cargasCorpusSintetico ?? 0)).toBe(0)
    await page.getByText('Índice del material', { exact: true }).click()
    await expect.poll(() => page.evaluate(() => window.__cargasCorpusSintetico)).toBe(1)
    await expect(page.getByRole('table').first()).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    const despues = await page.evaluate(() => ({ estudio: window.__leerProgresoSintetico(), nbme: window.__leerNbmeSintetico() }))
    expect(despues).toEqual(antes)
    expect(errores).toEqual([])
  })
  test('cajas omite el material ausente sin perder su historial ni ocupar el lugar válido', async ({ page }) => {
    const errores = await abrir(page, '/?escena=huerfanos#hoy')
    await expect(page.getByRole('heading', { name: 'Hoy', exact: true })).toBeVisible()
    const antes = await page.evaluate(() => window.__leerProgresoSintetico().progreso)
    await expect(page.getByRole('img', { name: 'cajas: 0 de 1', exact: true })).toBeVisible()
    await page.getByRole('button', { name: /(Empezar|Seguir con) las cajas/ }).click()
    await expect(page.getByRole('textbox', { name: 'Tu respuesta', exact: true })).toBeVisible()
    await expect(page.getByText('Bloque 1 de 1 · Paso 1 de 1', { exact: true })).toBeVisible()
    await expect(page.getByRole('progressbar', { name: 'Cajas hechas', exact: true })).toHaveAttribute('max', '1')
    const despues = await page.evaluate(() => window.__leerProgresoSintetico())
    expect(despues.progreso).toEqual(antes)
    expect(Object.keys(despues.conceptosVistos)).toEqual(['QA-VALIDO'])
    expect(despues.progreso['QA-OBSOLETO']).toEqual(antes['QA-OBSOLETO'])
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    expect(errores).toEqual([])
  })
})
