import { expect, test } from '@playwright/test'

for (const width of [390, 1280]) test.describe(`recuperación de la meta a ${width}px`, () => {
  test.use({ viewport: { width, height: 844 }, reducedMotion: 'reduce' })
  test('se abre a petición, distingue dominio y trabajo y retoma la misma cola de Hoy', async ({ page }) => {
    await page.clock.install({ time: new Date('2026-10-05T11:30:00Z') })
    await page.goto('/?escena=atraso#progreso')
    const panel = page.locator('details').filter({ has: page.getByText('Ponerme al día con la meta', { exact: true }) })
    await expect(panel).not.toHaveAttribute('open', '')
    await expect(page.getByRole('button', { name: 'Empezar recuperación de Hoy' })).toHaveCount(0)
    await panel.locator('summary').click()
    await expect(panel).toContainText('dominio demostrado')
    await expect(panel).toContainText('primeras respuestas')
    await expect(panel).toContainText('Primero los repasos vencidos')
    await expect(page.getByRole('button', { name: 'Empezar recuperación de Hoy' })).toBeEnabled()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.getByRole('button', { name: 'Empezar recuperación de Hoy' }).click()
    await expect(page.getByRole('textbox', { name: 'Tu respuesta', exact: true })).toBeVisible()
    await expect(page.locator('.session-step-label')).toContainText('Paso 1 de 4')
  })
  test('el viernes la distancia es informativa y no abre recuperación', async ({ page }) => {
    await page.clock.install({ time: new Date('2026-10-09T11:30:00Z') })
    await page.goto('/?escena=atraso#progreso')
    await page.getByText('Ponerme al día con la meta', { exact: true }).click()
    await expect(page.locator('.recuperacion-meta')).toContainText('El viernes queda libre')
    await expect(page.getByRole('button', { name: 'Empezar recuperación de Hoy' })).toHaveCount(0)
    await expect(page.getByRole('button', { name: 'Retomar mi sesión pendiente' })).toHaveCount(0)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  })
  test('retoma la cola exacta de conceptos en su paso guardado', async ({ page }) => {
    await page.clock.install({ time: new Date('2026-10-05T11:30:00Z') })
    await page.goto('/?escena=atraso&retomar=concepto#progreso')
    const progresoAntes = await page.evaluate(() => window.__leerProgresoSintetico().progreso)
    await page.getByText('Ponerme al día con la meta', { exact: true }).click()
    await page.getByRole('button', { name: 'Retomar mi sesión pendiente' }).click()
    await expect(page.locator('.app')).toHaveAttribute('data-view', 'estudio')
    await expect(page.getByRole('heading', { name: 'Sesión sintética guardada', exact: true })).toBeVisible()
    await expect(page.getByRole('textbox', { name: 'Tu respuesta', exact: true })).toBeVisible()
    await expect(page.locator('.avance')).toHaveAttribute('aria-label', 'Pregunta 2 de 3')
    await expect(page.locator('.pista')).toContainText('Pista 1:')
    const estado = await page.evaluate(() => window.__leerProgresoSintetico())
    expect(estado.progreso).toEqual(progresoAntes)
    expect(estado.reanudable).toMatchObject({ conceptIds: ['C8', 'C4', 'C8'], indice: 1, sessionId: 'conceptos-guardados', versionFormato: 3, cantidadInicial: 2,
      paso: { pistas: 1, confianza: 2 } })
  })
  test('retoma una sesión NBME pausada en su explicación, conservando el intento', async ({ page }) => {
    await page.clock.install({ time: new Date('2026-10-05T11:30:00Z') })
    await page.goto('/?escena=atraso&retomar=nbme#progreso')
    const intentosAntes = await page.evaluate(() => window.__leerNbmeSintetico().attempts)
    await page.getByText('Ponerme al día con la meta', { exact: true }).click()
    await page.getByRole('button', { name: 'Retomar mi sesión pendiente' }).click()
    await expect(page.locator('.app')).toHaveAttribute('data-view', 'preguntas')
    await expect(page.locator('.nbme-player')).toContainText('Preguntas sintéticas pendientes')
    await expect(page.locator('.nbme-feedback')).toContainText('Vamos a repasarla')
    await expect(page.locator('.nbme-player-header')).toContainText('Primera vuelta: 1/2')
    const estado = await page.evaluate(() => window.__leerNbmeSintetico())
    expect(estado.attempts).toEqual(intentosAntes)
    expect(estado.activeSessionId).toBe('preguntas-guardadas')
    expect(estado.sessions['preguntas-guardadas'].paused).toBe(false)
    await expect(page.getByRole('button', { name: 'Continuar', exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Continuar', exact: true }).click()
    await expect(page.getByRole('heading', { name: 'Pregunta 2 de 2', exact: true })).toBeVisible()
    await expect(page.locator('.nbme-player-header')).toContainText('Primera vuelta: 1/2')
  })
  test('un resumen conceptual terminado no oculta la sesión NBME pendiente', async ({ page }) => {
    await page.clock.install({ time: new Date('2026-10-05T11:30:00Z') })
    await page.goto('/?escena=atraso&retomar=nbme-resumen#progreso')
    const bookmarkAntes = await page.evaluate(() => window.__leerProgresoSintetico().reanudable)
    const bancoAntes = await page.evaluate(() => window.__leerNbmeSintetico())
    expect(bookmarkAntes.indice).toBe(bookmarkAntes.conceptIds.length)
    await page.getByText('Ponerme al día con la meta', { exact: true }).click()
    await page.getByRole('button', { name: 'Retomar mi sesión pendiente' }).click()
    await expect(page.locator('.app')).toHaveAttribute('data-view', 'preguntas')
    await expect(page.locator('.nbme-feedback')).toContainText('Vamos a repasarla')
    const bancoDespues = await page.evaluate(() => window.__leerNbmeSintetico())
    expect(bancoDespues.activeSessionId).toBe('preguntas-guardadas')
    expect(Object.keys(bancoDespues.sessions)).toEqual(Object.keys(bancoAntes.sessions))
    expect(bancoDespues.sessions['preguntas-guardadas'].initial).toEqual(bancoAntes.sessions['preguntas-guardadas'].initial)
    expect(bancoDespues.attempts).toEqual(bancoAntes.attempts)
    expect(await page.evaluate(() => window.__leerProgresoSintetico().reanudable)).toEqual(bookmarkAntes)
  })
  for (const tipo of ['concepto', 'nbme']) test(`un fallo al retomar ${tipo} se ve junto al botón y permite reintentar`, async ({ page }) => {
    await page.clock.install({ time: new Date('2026-10-05T11:30:00Z') })
    await page.goto(`/?escena=atraso&retomar=${tipo}-error#progreso`)
    await page.getByText('Ponerme al día con la meta', { exact: true }).click()
    await page.getByRole('button', { name: 'Retomar mi sesión pendiente' }).click()
    const panel = page.locator('.recuperacion-meta')
    await expect(panel.getByRole('alert')).toContainText('sintética')
    await expect(panel.getByRole('alert')).toBeInViewport()
    await expect(page.locator('.app')).toHaveAttribute('data-view', 'progreso')
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.getByRole('button', { name: 'Retomar mi sesión pendiente' }).click()
    await expect(page.locator('.app')).toHaveAttribute('data-view', tipo === 'concepto' ? 'estudio' : 'preguntas')
  })
  test('también retoma desde Cómo va todo en Hoy', async ({ page }) => {
    await page.clock.install({ time: new Date('2026-10-05T11:30:00Z') })
    await page.goto('/?escena=atraso&retomar=nbme#hoy')
    await expect(page.getByRole('region', { name: 'Tu sesión guardada', exact: true })
      .getByRole('button', { name: 'Retomar mi sesión pendiente', exact: true })).toBeVisible()
    await page.getByText('Cómo va todo', { exact: true }).click()
    await page.getByText('Ponerme al día con la meta', { exact: true }).click()
    await page.locator('.recuperacion-meta').getByRole('button', { name: 'Retomar mi sesión pendiente', exact: true }).click()
    await expect(page.locator('.app')).toHaveAttribute('data-view', 'preguntas')
    await expect(page.locator('.nbme-feedback')).toContainText('Vamos a repasarla')
  })
})
